// settings.js
// credit by Kevin tech 

const config = require('./setting/config');


const settings = {
  SESSION_ID: config.SESSION_ID || "starcore~eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiK05OcENVNGJBYVVnV2JLS0R2cncxMDJ2dXd1SCtvK1hsYTk3Z2lVMC9uVT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWmJNR3hrbURjUnE5cXFCQzBCRUhKVDA2SEQ3bGkydzRCWXFwVTdJQUxUQT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJVRU1CMDRQUk9od2Z3Ykg3UVJSZ0tpVEhaQUtPWllOUFNIQlM0ZUYwNFhJPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJwQ1RSQkRtY3hyenlzTFVGY29ZSWk0OEtqMS83cEdZMG55NVU3SjhGb2wwPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImlOZ3F3MUZnYjNBZ2Z4Q0d1YmxSMDVKY0NjYlZ2dXA5dGJoOTRqcVFQVm89In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IisrNWt2cXVLd2JIY0x6NlJwUUlrOVZHSDlVWFB5dXNKTmVYUEVNVml4aG89In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicUowMytCZklMWWhyTUwrbGc2azNZN0JBNU01N1VRV2NYODREdG9zdlkxST0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWTZiRmdqMFZPN3B3Zmg4dUo3a0ZRTFJ3SVRHM3FtVkVFUzdmVmxTUHNrQT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Im91ZFB0QUZYU3hkRmRFVjN4NUZsdUo2ei9qL0VPR1N2c1dqRFJRdG5tWjY3SXphMmlkOS9aTnhEcXRLOUNPdEpJbTdINlVqMjRwOGFBVTIvQjFnaGpBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjAxLCJhZHZTZWNyZXRLZXkiOiJHWURmbzlkM1h5UWdOSWFGVVdMbXllQStyL1dGWXhuUTJJbWM4dzVEWTRvPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6dHJ1ZSwicGFpcmluZ0NvZGUiOiJTQ1hMNEwyViIsIm1lIjp7ImlkIjoiMjU0NzIzNDEzMjQ0OjEyQHMud2hhdHNhcHAubmV0IiwibGlkIjoiNjQ5NzA2OTE3Mzk3MzY6MTJAbGlkIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNNbjl4cG9IRUx1R25NWUdHQU1nQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJXbW5LeXlyMlM0UFBramxWRUo0ZmIzUXNlaXppb0F2TXpqYklqYi9oL3dBPSIsImFjY291bnRTaWduYXR1cmUiOiJaT1plQ01pY0xPOHpFUzlKWEQrdldvTVlwR3JiWDJ4TVRWOHlMMnNOa3JRYXpPN1JVYmRHNWVmc1FCekxkbjE4a1lFdFBGQWd4YlNMRUVKbm1tRDRDUT09IiwiZGV2aWNlU2lnbmF0dXJlIjoic0RFV2N5ZU1GSlJzcVhQWVhkaUNRVkJpUzVxbDhLd29lWkx1aXgzTGFtbjFjRFJHeDBvbTJJajFHZlk4V0hXWHB2SzI3SjJsZFFUNkZZNFZYYnM4aWc9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyNTQ3MjM0MTMyNDQ6MTJAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCVnBweXNzcTlrdUR6NUk1VlJDZUgyOTBMSG9zNHFBTHpNNDJ5STIvNGY4QSJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0FJSURRPT0ifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzU3ODcyOTY5LCJsYXN0UHJvcEhhc2giOiJQV2s1QiIsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBRHNjIn0=", // enter session id
  ownername: config.ownername || "ᴋᴇʟᴠɪɴ ᴛᴇᴄʜ", // Owner name
  botname: config.botname || "ᴠɪɴɪᴄ xᴍᴅ", // custom bot name
  prefa: config.prefa || ['.', '!'], // Command prefixes
  owner: config.owner || ["254723413244"] // Owner phone numbers
};

// Export settings for use in other modules
module.exports = settings;

// Watch for changes to this file and reload if updated
const fs = require('fs');
let file = require.resolve(__filename);
fs.watchFile(file, () => {
  fs.unwatchFile(file);
  console.log('\x1b[0;32m' + __filename + ' \x1b[1;32mupdated!\x1b[0m');
  delete require.cache[file];
  require(file);
});
