// settings.js
// credit by Kevin tech 

const config = require('./setting/config');


const settings = {
  SESSION_ID: config.SESSION_ID || "starcore~eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoic0w2MzA3T1F0bW5jVjZnM3IvYVBJRVNjM1lvbUFMelFickN1K2duV0syST0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZ3lsMHhzNXdlTHNMMTRkRFRmaXdWZEVyUm5SZXB3WEExbFB1RWZ5eVd5OD0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJjSFd6N0U2MkdiZFZ0L0ZOcFBVbWtJaEl0TWg0N2dwOFhEM1UxWjdSNmxVPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJkMXFyWFRzY0EzWEhaYlZYZm9FQ1Urem1FTEZaTWozelJoc3ZETFgwc1RjPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IitCK0plR0hybkkyWncxMXRSYlF0RGlRc3BFTTF3bk1PQzF5ZytkVXl2bDA9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InAxYXJCakFRS0JVaDNtSGRDYm9wanVCQ1NJcnlGTlA2VUdwdWtQOEgzd0k9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiS05QWlNSQURNdE9WZWVrVi9WWGZRanEvWTdkL2V1dW96ZHZ6bWRoSWJFMD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiL3Jtc05ETGM1R056cFFMSmNybEIwZURLdEk3VkgycnBUYlZQOU1TRlFRWT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InVhYU9iTG95ejVJbDY5Q0NuTWJ2Q1lhN3hLMmx5K01XZHV0RGJRQndzYnlWcCtpVjlMWkZvRXZJRytKQWlrRW5venRXVjFjSUFjZWNIQi9LN3ZsQURBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NzEsImFkdlNlY3JldEtleSI6IlVjVDRhN1R6OWRJbW4wdXVaWVpUdXhscnhIM3JORTFuUHY3azg1RGdzVWM9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMjU0Nzk4NDU3MDM5QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjZCQzZDM0ZGNzZBNTAwNUM1OUExRDI2OEU2M0I5NTkwIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NTc0NTg0OTB9XSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJyZWdpc3RlcmVkIjp0cnVlLCJwYWlyaW5nQ29kZSI6IlkzN1g1WldWIiwibWUiOnsiaWQiOiIyNTQ3OTg0NTcwMzk6MzBAcy53aGF0c2FwcC5uZXQiLCJsaWQiOiI2NzEzNTI3MTM1ODUyODozMEBsaWQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ0w3bnM4RUhFS2ZnZ3NZR0dCRWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6IkljdTNZWk5rc0ZtNHNHY0xZVG5oTFJSQTgxRVVjQ0tsc0NMdUx0RktFMzA9IiwiYWNjb3VudFNpZ25hdHVyZSI6Im1lRVA4Y1hjclVtS0pPZTQvbVVaaENIb3hPK2loUU1LTXRveHlRc0FaNDNTT1NSMGQyWTRrQzY2ak1XSlFXTEcyVFk5MGw2UDVydTQzaU1UclBneEFBPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJrK1lhSGVsUDZkZkU0YWxuNVljUFpNb1ErR3N2b1NGOTJnc0NYbmVNRDkxekNlVmhpWDFTMFZsL2NmT1hxSnlsRTN3eXFIMDcxWmpreHhacXJnc1NCdz09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjI1NDc5ODQ1NzAzOTozMEBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJTSEx0MkdUWkxCWnVMQm5DMkU1NFMwVVFQTlJGSEFpcGJBaTdpN1JTaE45In19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwicm91dGluZ0luZm8iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDQUlJQlE9PSJ9LCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3NTc0NTg0ODcsImxhc3RQcm9wSGFzaCI6IjNSOVozOSIsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBSmh3In0=", // enter session id
  ownername: config.ownername || "ᴋᴇʟᴠɪɴ ᴛᴇᴄʜ", // Owner name
  botname: config.botname || "ᴠɪɴɪᴄ xᴍᴅ", // custom bot name
  prefa: config.prefa || ['.', '!'], // Command prefixes
  owner: config.owner || ["254798457039"] // Owner phone numbers
};

// Export settings for use in other modules
module.exports = settings;

// Watch for changes to this file and reload if updated
const fs = require('fs');
let file = require.resolve(__filename);
fs.watchFile(file, () => {
  fs.unwatchFile(file);
  console.log('\x1b[0;32m' + __filename + ' \x1b[1;32mupdated!\x1b[0m');
  delete require.cache[file];
  require(file);
});
